(library
    (name directconnectstubs)
    (wrapped false)
    (modules)
    (foreign_stubs
        (language c)
        (names
            che3_c
        )
        (flags (:standard -I%{project_root}/../.. -I../../utils/cdk))
    )
)

(library
    (name directconnect)
    (flags
        (:standard -w -3 -w -27 -w -67 -w -35 -w -69 -w -32 -w -16 -w -6)
    )
    (wrapped false)
    (libraries daemoncommon directconnectstubs)
)
