(library
    (name autoconf)
    (public_name mldonkey.autoconf)
    (flags
        (:standard -w -3 -w -50 -w -27 -w -67 -w -69)
    )
    (wrapped false)
    (modules
        autoconf
    )
)

(library
    (name utils_stubs)
    (public_name mldonkey.utils_stubs)
    (modules)
    (foreign_stubs
        (language c)
        (names
            md4_c
            md4_comp
            charsetstubs
            tiger
            tiger_stubs
            hashes_stubs
            sha1_c
            md5_c
            fst_hash
            magiclib_stub
            CryptoPP_stubs
        )
        (flags (:standard -I%{project_root}/../.. -I../cdk))
    )
    (foreign_stubs
        (language cxx)
        (names CryptoPP)
    )
)

(library
    (name utils)
    (public_name mldonkey.utils)
    (flags
        (:standard -w -3 -w -27 -w -67 -w -35 -w -69 -w -32)
    )
    (wrapped false)
    (libraries mldonkey.cdk mldonkey.autoconf mldonkey.utils_stubs)
    (modules
        bitv
        charset
        date
        gettext
        http_lexer
        indexer
        indexer1
        indexer2
        intmap
        intset
        levenshtein
        magic
        magic_magic
        magiclib
        md4
        misc
        misc2
        options
        queues
        set2
        store
        stringMap
        threadPool
        url
        verificationBitmap
    )
)
