(library
    (name cdk)
    (modules
        arg2
        array2
        bzip2
        bzlib
        file
        filename2
        filepath
        filesystem
        gd
        genlex2
        gzip
        hashtbl2
        heap
        list2
        printexc2
        printf2
        string2
        tar
        syslog
        unix2
        unix32
        zip
        zlib2
        zlib
        fifo)
    (foreign_stubs
        (language c)
        (names bzip2stubs gdstubs heap_c zlibstubs)
    )
    (libraries IO unix str threads camlp-streams)
    (flags (:standard -w -32 -w -50 -w -27 -w -35 -w -69))
)