(library
    (name commonstubs)
    (public_name mldonkey.commonstubs)
    (wrapped false)
    (modules)
    (foreign_stubs
        (language c)
        (names
            commonHasher_c
        )
        (flags (:standard -I%{project_root}/../.. -I../../utils/cdk))
    )
)

(library
    (name daemoncommon)
    (public_name mldonkey.daemoncommon)
    (flags
        (:standard -w -3 -w -27 -w -67 -w -35 -w -69 -w -32)
    )
    (wrapped false)
    (libraries
        mldonkey.utils
        mldonkey.net
        mldonkey.mp3tagui
        mldonkey.xmllight
        mldonkey.ocamlrss
        mldonkey.cdk
        mldonkey.commonstubs
    )
)
