(* main.ml *)

open Printf2

let () =
  BasicSocket.force_link ();
  BasicSocket.add_timer 0.1 (fun _ ->
    Printf2.force_link ();
    Bitv.force_link ();
    Magiclib.force_link ();
    Charset.force_link ();
    Md4.force_link ();
    TcpServerSocket.force_link ();
    Ip_set.force_link ();
    UdpSocket.force_link ();
    Geoip.force_link ();
    Ip.force_link ();
    TcpBufferedSocket.force_link ();
    Cobs.force_link ();
    BasicSocket.force_link ();
    Rss_io.force_link ();
    Rss_date.force_link ();
    Zlib.force_link ();
    Bzlib.force_link ();
    Gd.force_link ();
    Filename2.force_link ();
    Heap.force_link ();
    Unix32.force_link ();
    Xml.force_link ();
    (* Mp3.force_link (); *)
    (* Mp3_args.force_link (); *)
    (* SlskServers.force_link ();
    SlskInteractive.force_link ();
    SlskMain.force_link ();
    OpennapComplexOptions.force_link ();
    OpennapServers.force_link ();
    OpennapInteractive.force_link ();
    OpennapMain.force_link ();
    OpennapOptions.force_link ();
    DcClients.force_link ();
    DcInteractive.force_link ();
    DcShared.force_link ();
    DcServers.force_link ();
    DcMain.force_link ();
    DcComplexOptions.force_link (); *)
    BTStats.force_link ();
    BTGlobals.force_link ();
    BTOptions.force_link ();
    BTClients.force_link ();
    Kademlia.force_link ();
    BT_DHT.force_link ();
    BTTracker.force_link ();
    BTComplexOptions.force_link ();
    BTInteractive.force_link ();
    BTMain.force_link ();
    GnutellaGlobals.force_link ();
    GnutellaComplexOptions.force_link ();
    GnutellaServers.force_link ();
    GnutellaMain.force_link ();
    GnutellaOptions.force_link ();
    GnutellaInteractive.force_link ();
    GnutellaSupernode.force_link ();
    GnutellaClients.force_link ();
    FasttrackServers.force_link ();
    FasttrackProto.force_link ();
    FasttrackGlobals.force_link ();
    FasttrackPandora.force_link ();
    FileTPGlobals.force_link ();
    FileTPMain.force_link ();
    FileTPInteractive.force_link ();
    FileTPComplexOptions.force_link ();
    (* OpenFTMain.force_link ();
    OpenFTServers.force_link ();
    OpenFTComplexOptions.force_link ();
    OpenFTInteractive.force_link ();
    G2Proto.force_link ();
    G2Supernode.force_link ();
    G2Pandora.force_link (); *)
    (* ServerMain.force_link (); *)
    DonkeyOptions.force_link ();
    DonkeyMain.force_link ();
    DonkeyPandora.force_link ();
    DonkeyProtoServer.force_link ();
    DonkeySearch.force_link ();
    DonkeyComplexOptions.force_link ();
    DonkeyInteractive.force_link ();
    DonkeyShare.force_link ();
    DonkeyNodesDat.force_link ();
    DonkeyGlobals.force_link ();
    DonkeyOvernet.force_link ();
    DonkeyOneFile.force_link ();
    DonkeyServers.force_link ();
    DonkeyFiles.force_link ();
    DonkeyThieves.force_link ();
    DonkeySupernode.force_link ();
    DonkeyReliability.force_link ();
    DonkeyStats.force_link ();
    DonkeyClient.force_link ();
    DriverCommands.force_link ();
    DriverInterface.force_link ();
    CommonUser.force_link ();
    CommonResult.force_link ();
    CommonHosts.force_link ();
    CommonSources.force_link ();
    CommonShared.force_link ();
    CommonFile.force_link ();
    GuiEncoding.force_link ();
    CommonNetwork.force_link ();
    CommonClient.force_link ();
    CommonComplexOptions.force_link ();
    CommonHasher.force_link ();
    CommonInteractive.force_link ();
    CommonUploads.force_link ();
    CommonGlobals.force_link ();
    CommonIndexing.force_link ();
    CommonSwarming.force_link ();
    CommonBlocking.force_link ();
    CommonServer.force_link ();
    GuiDecoding.force_link ();
    CommonWeb.force_link ();
    CommonSearch.force_link ();
    CommonOptions.force_link ();
    CommonRoom.force_link ();
    CommonStats.force_link ();
    CommonPictures.force_link ();
    CommonUserDb.force_link ();
    DriverMain.init_1 ();
    DriverMain.init_2 ();
    );
  CommonMain.main_loop ()
