(library
    (name donkey)
    (public_name mldonkey.donkey)
    (flags
        (:standard -w -3 -w -27 -w -67 -w -35 -w -69 -w -32)
    )
    (wrapped false)
    (libraries
        bitstring
        mldonkey.utils
        mldonkey.net
        mldonkey.mp3tagui
        mldonkey.xmllight
        mldonkey.ocamlrss
        mldonkey.cdk
        mldonkey.commonstubs
        mldonkey.daemoncommon
    )
)